-- TODO Add a foreign key column to employee-table refrencing company-table
ALTER TABLE EMPLOYEE
ADD COLUMN COMPANY_ID NUMBER(19);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT COMPANY_FK FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY (ID);
